# Generated by Django 5.1 on 2024-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfree_payment',
            name='cf_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashfree_payment',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
